#!/bin/bash
echo "total 48
drwxrwxr-x 2 vagrant vagrant 4096 Oct  2 15:06 .
drwxrwxr-x 6 vagrant vagrant 4096 Oct  1 19:13 ..
-rwxrwxr-x 1 vagrant vagrant   32 Oct  1 19:13 0-hello_world
-rwxrw-r-- 1 vagrant vagrant   28 Oct  2 03:24 1-confused_smiley
-rwxrw-r-- 1 vagrant vagrant   28 Oct  2 03:30 2-hellofile
-rwxrw-r-- 1 vagrant vagrant   39 Oct  2 06:57 3-twofiles
-rwxrw-r-- 1 vagrant vagrant   29 Oct  2 07:18 4-lastlines
-rwxrw-r-- 1 vagrant vagrant   29 Oct  2 07:21 5-firstlines
-rwxrw-r-- 1 vagrant vagrant   40 Oct  2 12:05 6-third_line
-rwxrw-r-- 1 vagrant vagrant   87 Oct  2 14:58 7-file
-rw-rw-r-- 1 vagrant vagrant   18 Oct  2 15:06 8-cwd_state
-rw-rw-r-- 1 vagrant vagrant   26 Oct  1 19:13 README.md"  > ls_cwd_content
